open-cluster-management-io/sdk-go

pkg/cloudevents/generic/agentclient.go, pkg/cloudevents/generic/agentclient_test.go, pkg/cloudevents/generic/interface.go, pkg/cloudevents/generic/options/mqtt/agentoptions.go, pkg/cloudevents/generic/options/mqtt/agentoptions_test.go, pkg/cloudevents/generic/options/mqtt/options.go, pkg/cloudevents/generic/options/mqtt/options_test.go, pkg/cloudevents/generic/options/mqtt/sourceoptions.go, pkg/cloudevents/generic/options/mqtt/sourceoptions_test.go, pkg/cloudevents/generic/sourceclient.go, pkg/cloudevents/generic/sourceclient_test.go, pkg/cloudevents/generic/types/types.go, pkg/cloudevents/work/agent/client/manifestwork.go, test/integration/cloudevents/cloudevents_test.go, test/integration/cloudevents/source/client.go, test/integration/cloudevents/suite_test.go
reorg the topics to:
- SourceEvents topic (`sources/+/clusters/+/sourceevents`) is a topic for sources to publish their resource create/update/delete events or status resync events
- AgentEvents topic (`sources/+/clusters/+/agentevents`) is a topic for agents to publish their resource status update events or spec resync events
- (Optional) SourceBroadcast (`sources/+/sourceevents`)  is a topic for a source to publish its events to all agents
- (Optional) AgentBroadcast (`clusters/+/agentevents`) is a topic for a agent to publish its events to all sources
=> :seedling: reorg the topics

pkg/cloudevents/generic/options/grpc/agentoptions.go, pkg/cloudevents/generic/options/grpc/options.go, pkg/cloudevents/generic/options/grpc/sourceoptions.go
This PR tries to add error handler to the GRPC option that cloudevent client relays on.
Ref: 
- https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md
- https://stackoverflow.com/questions/66353603/correct-way-to-perform-a-reconnect-with-grpc-client
Fixes #
=> 🐛 add error handler for grpc options.

pkg/cloudevents/work/agent/codec/manifest.go, pkg/cloudevents/work/agent/codec/manifestbundle.go, pkg/cloudevents/work/source/codec/manifestbundle.go
This PR tries to fix the `resourceversion` convert issue in cloudevent decoder, the original issue is as follow:
```bash
failed to decode cloudevent: failed to get resourceversion extension: cannot convert 1 to string
```
Fixes #
=> 🐛 fix resource version conversion.

pkg/cloudevents/generic/baseclient.go
During maestro integration testing, there is error reports if you cancel the context.
```
E0320 21:09:47.076315   11088 baseclient.go:87] the cloudevents client is disconnected, read tcp [::1]:53750->[::1]:1883: use of closed network connection
panic: send on closed channel
goroutine 47 [running]:
open-cluster-management.io/sdk-go/pkg/cloudevents/generic.(*baseClient).sendReceiverSignal(0x32123e0?, 0x1)
/Users/chuyang/go/src/github.com/clyang82/maestro/vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/baseclient.go:213 +0x86
open-cluster-management.io/sdk-go/pkg/cloudevents/generic.(*baseClient).connect.func1()
/Users/chuyang/go/src/github.com/clyang82/maestro/vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/baseclient.go:91 +0x3c5
created by …
```
=> :bug: Checking if a Channel is Open or Closed

pkg/cloudevents/generic/options/kafka/options.go, pkg/cloudevents/generic/options/kafka/options_test.go, pkg/cloudevents/generic/optionsbuilder_test.go
We found that the source client cannot receive the events from agentevents.maestro.* that is because the source client did not start to watch the new topic (agentevents.maestro.cluster1) when the agent is sending the events to that topic. We set as `latest` in the past. when the source client is ready to consume the event from that topic, the `latest` means automatically reset the offset to the largest offset so that the previous events are missed. set as `earliest` means automatically reset the offset to the smallest offset. it can resolve that issue.
Fixes #
=> :bug: set auto.offset.reset as earliest

pkg/cloudevents/generic/agentclient.go, pkg/cloudevents/generic/sourceclient.go, pkg/cloudevents/work/agent/client/manifestwork.go, pkg/cloudevents/work/store/informer.go
1. This PR mainly addresses a race condition where a work status update can overwrite the DeletionTimestamp, preventing the resource from being deleted. The issue occurs when an update event is followed immediately by a delete event from the source, causing the agent to skip deletion. 
To resolve this, we now verify the resource version before updating the agent store for work status update.
3. Additionally, any update event that follows a delete event for the same resource from the source will be ignored from agent side.
4. In this PR we've also removed a duplicate debug log that printed the received event. (that is printed in [baseclient.go](https://github.com/open-cluster-management-io/sdk-go/blob/1afb1eab940dc51bf39fe81f38fac4de91a3c5ca/pkg/cloudevents/generic/baseclient.go#L161)) …
=> 🐛 fix race condition between work status update and deletion.

pkg/cloudevents/work/common/common.go, pkg/cloudevents/work/source/codec/manifestbundle.go, pkg/cloudevents/work/source/codec/manifestbundle_test.go, pkg/cloudevents/work/store/base.go, pkg/cloudevents/work/store/local.go, pkg/cloudevents/work/utils/utils.go, pkg/cloudevents/work/utils/utils_test.go
Compare status update event sequence ID in work source client to ensure that the messages received by the source client are in the same order as the messages sent by the agent client
This will help to guard against if some message queues cannot guarantee the order of the messages they send
=> :seedling: compare status update event sequence ID in source client

pkg/cloudevents/generic/baseclient.go
If the event is too large, it will cut off the error message in the log
=> :seedling: avoid to print whole event in the error log

pkg/cloudevents/generic/baseclient.go
Currently, we set the client to nil when a client start reconnecting, this may cause nil point
```
2024-10-17T18:53:15.218Z	ERROR	generic/baseclient.go:88	the cloudevents client is disconnected, ping handler error: PINGRESP timed out
open-cluster-management.io/sdk-go/pkg/cloudevents/generic.(*baseClient).connect.func1
/go/pkg/mod/open-cluster-management.io/sdk-go@v0.14.1-0.20241009075853-0c5ba39fd113/pkg/cloudevents/generic/baseclient.go:88
2024-10-17T18:53:15.219Z	ERROR	generic/baseclient.go:164	failed to receive cloudevents, error while opening the inbound connection: use of closed network connection
open-cluster-management.io/sdk-go/pkg/cloudevents/generic.(*baseClient).subscribe.func1.1
/go/pkg/mod/open-cluster-management.io/sdk-go@v0.14.1-0.20241009075853-0c5ba39fd113/pkg/cloudevents/ …
```
=> :bug: using local flag instead of setting client to nil

pkg/cloudevents/work/store/informer.go, test/integration/cloudevents/agent/agent.go, test/integration/cloudevents/cloudevents_kafka_test.go, test/integration/cloudevents/source/client.go
Using informer hassynced  to determine if the store inited 
Fix the issue: 
When a source client send the events before the agent client informer is not synced, the event will not be resynced the events in the agent informer
=> :bug: determine if ce informer store inited using informer hassynced

pkg/cloudevents/generic/options/grpc/options.go, pkg/cloudevents/generic/options/grpc/options_test.go, pkg/cloudevents/generic/optionsbuilder_test.go, test/integration/cloudevents/broker/grpc.go, test/integration/cloudevents/cloudevetns_grpc_test.go, test/integration/cloudevents/suite_test.go, test/integration/cloudevents/util/grpc.go
This PR introduces keepalive parameters to the cloudevents client using gRPC. By default, these parameters are disabled. Users can optionally enable it to detect broken gRPC connections. MQTT has similar feature to detect the half-open connection.
Fixes #
=> ✨ enable grpc keepalive.

pkg/cloudevents/generic/types/types.go, pkg/cloudevents/work/agent/codec/manifestbundle.go, pkg/cloudevents/work/clientbuilder.go, pkg/cloudevents/work/statushash/statushash.go
Introduce the status hash extension in the status event, the source/broker may choose to save this hash to avoid recalculate the status hash
=> :seedling: introduce the status hash extension

pkg/cloudevents/generic/agentclient.go, pkg/cloudevents/generic/metrics_collector.go, pkg/cloudevents/generic/metrics_collector_test.go, pkg/cloudevents/generic/sourceclient.go
This PR adds more labels (subresource and action) to cloudevent_received_total and cloudevents_sent_total metrics, so that developers can query sent/received coudevents for different type, eg, spec create, status update, resync request, resync response...
Fixes #
=> 🌱 enhance cloud events metrics.

pkg/cloudevents/generic/options/cert/cert_rotation.go, pkg/cloudevents/generic/options/grpc/options.go, pkg/cloudevents/generic/options/grpc/options_test.go, pkg/cloudevents/generic/options/mqtt/options.go, pkg/cloudevents/generic/optionsbuilder.go, pkg/cloudevents/generic/optionsbuilder_test.go, test/integration/cloudevents/broker/grpc.go, test/integration/cloudevents/certrotation_grpc_test.go, test/integration/cloudevents/certrotation_mqtt_test.go, test/integration/cloudevents/certrotation_test.go, test/integration/cloudevents/cloudevetns_grpc_test.go, test/integration/cloudevents/suite_test.go, test/integration/cloudevents/util/grpc.go
This PR enables the client certificate auto reload for the grpc cloudevents client, so that client doesn't need to restart when client certificate is rotated.
Fixes #
=> ✨ enable certificate auto reload for grpc client.

pkg/cloudevents/generic/options/grpc/options.go, pkg/cloudevents/generic/options/grpc/options_test.go, pkg/cloudevents/generic/options/mqtt/options.go, pkg/cloudevents/generic/optionsbuilder_test.go, test/integration/cloudevents/options_racing_grpc_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
This PR ensures one single connection for each grpc/mqtt option.
Fixes #
=> 🌱 single connection for grpc options.

pkg/cloudevents/generic/options/cert/cert_rotation.go, pkg/cloudevents/generic/options/grpc/options.go
In the eventgride, the CA is not provided when connect to MQTT. the CA is from system cert pool.
Fixes #. https://issues.redhat.com/browse/ACM-19065
=> :bug: Allow CA is not provided

pkg/cloudevents/clients/cluster/client.go, pkg/cloudevents/clients/csr/client.go, pkg/cloudevents/clients/errors/errors.go, pkg/cloudevents/clients/errors/errors_test.go, pkg/cloudevents/clients/work/agent/client/manifestwork.go, pkg/cloudevents/clients/work/source/client/manifestwork.go, pkg/cloudevents/generic/baseclient.go, pkg/cloudevents/server/grpc/server.go
If the grpc server based on a kube server, when it returns a grpc error that contains kube status error, we convert it directly in the kube based ce clients
Fixes #
=> :seedling:  convert grpc error to kube status error

pkg/helpers/csr.go, pkg/helpers/csr_test.go
Move the `DefaultSignerWithExpiry` from https://github.com/open-cluster-management-io/addon-framework/blob/main/pkg/utils/csr_helpers.go to sdk and make it can be compatible with PKCS#8 key
Fixes #
=> :seedling:  csr helper

pkg/cel/common/values.go, pkg/cel/library/cost.go, pkg/cel/library/cost_test.go
https://github.com/open-cluster-management-io/ocm/issues/843
https://github.com/open-cluster-management-io/ocm/issues/955
=> :sparkles: add CEL cost estimator

pkg/cel/library/conditions.go, pkg/cel/library/conditions_test.go
Adding ConditionsLib with a helper function to streamline status condition checks. Checking for the existence of conditions can be quite verbose with null checks at every level. The `hasConditions` function makes it easy to verify if a status map has any conditions before doing additional processing with `.exists(...)` or `.filter(...)`
https://github.com/open-cluster-management-io/ocm/pull/910#discussion_r2075052856
=> :sparkles: Conditions CEL lib for easier status condition checks
