open-cluster-management-io/sdk-go

pkg/cloudevents/generic/options/mqtt/agentoptions.go
pkg/cloudevents/generic/options/mqtt/agentoptions_test.go
pkg/cloudevents/generic/options/mqtt/options.go
pkg/cloudevents/generic/options/mqtt/options_test.go
pkg/cloudevents/generic/options/mqtt/sourceoptions.go
pkg/cloudevents/generic/options/mqtt/sourceoptions_test.go
pkg/cloudevents/generic/types/types.go

:sparkles: add mqtt topics to options

---

pkg/cloudevents/generic/options/mqtt/agentoptions_test.go
pkg/cloudevents/generic/options/mqtt/options.go
pkg/cloudevents/generic/options/mqtt/options_test.go

introduce the timeout for the connection. if the connection is failed due to timeout, then throw the meaningful message for the troubleshooting.

:seedling: Add timeout for mqtt connection

---

pkg/cloudevents/generic/options/mqtt/options.go
pkg/cloudevents/generic/options/mqtt/options_test.go

:seedling: increasing the mqtt connection timeout

---

pkg/cloudevents/generic/options/mqtt/options.go
pkg/cloudevents/generic/options/mqtt/options_test.go
pkg/cloudevents/generic/types/types.go

:bug: support to get source from share topic

---

pkg/cloudevents/generic/agentclient.go
pkg/cloudevents/generic/baseclient.go
pkg/cloudevents/generic/interface.go
pkg/cloudevents/generic/options/mqtt/agentoptions.go
pkg/cloudevents/generic/options/mqtt/sourceoptions.go
pkg/cloudevents/generic/sourceclient.go
pkg/cloudevents/work/agent/client/manifestwork.go
pkg/cloudevents/work/agent/codec/manifest.go
pkg/cloudevents/work/agent/codec/manifest_test.go
pkg/cloudevents/work/agent/codec/manifestbundle_test.go
pkg/cloudevents/work/clientbuilder.go
pkg/cloudevents/work/common/common.go
pkg/cloudevents/work/internal/clientset.go
pkg/cloudevents/work/lister.go
pkg/cloudevents/work/source/client/manifestwork.go
pkg/cloudevents/work/source/codec/manifestbundle.go
pkg/cloudevents/work/source/codec/manifestbundle_test.go
pkg/cloudevents/work/source/handler/resourcehandler.go
pkg/cloudevents/work/utils/utiles_test.go
pkg/cloudevents/work/utils/utils.go
test/integration/cloudevents/agent/agent.go
test/integration/cloudevents/cloudevents_test.go
test/integration/cloudevents/manifestworksourceclient_test.go
test/integration/cloudevents/source/client.go
test/integration/cloudevents/suite_test.go

:sparkles: add work source client

---

pkg/cloudevents/work/configloader.go
pkg/cloudevents/work/configloader_test.go

:bug: should init the config loader in its constructor

---

pkg/cloudevents/generic/options/mqtt/agentoptions.go
pkg/cloudevents/generic/options/mqtt/agentoptions_test.go
pkg/cloudevents/generic/options/mqtt/options.go
pkg/cloudevents/generic/options/mqtt/sourceoptions.go
pkg/cloudevents/generic/options/mqtt/sourceoptions_test.go

:seedling:  allow to set the mqtt pub topic from context

---

pkg/cloudevents/README.md

update doc for cloudevents.
Fixes #

📖 update doc for cloudevents.

---

pkg/cloudevents/generic/agentclient.go
pkg/cloudevents/work/agent/handler/resourcehandler.go
pkg/cloudevents/work/source/client/manifestwork.go
test/integration/cloudevents/cloudevents_test.go
test/integration/cloudevents/manifestworksourceclient_test.go

remove version check for event based work client patch operation.
ref: https://issues.redhat.com/browse/ACM-10959

🌱 enhance resource version check for event based manifestwork patch. 

---

pkg/apis/work/v1/applier/workapplier.go
pkg/apis/work/v1/applier/workapplier_test.go

Fix the issue to remove annotations from work when it's nil in WorkApplier.Apply(). 
Fixes #

:bug: fix annotation and label removal issues in work

---

pkg/cloudevents/work/source/client/manifestwork.go
test/integration/cloudevents/agent/agent.go
test/integration/cloudevents/cloudevents_test.go
test/integration/cloudevents/manifestworksourceclient_test.go
test/integration/cloudevents/source/client.go

:seedling: using a fixed data type (bundle) for manifestwork source client

---

test/integration/cloudevents/cloudevents_test.go
test/integration/cloudevents/manifestworksourceclient_test.go

fix the flaky integration testing, in which the cloudevents client doesn't shut down gracefully.
Fixes #

🐛 fix flaky cloudevents testing.

---

pkg/cloudevents/generic/baseclient.go

:seedling: enhance pub/sub cloudevents debug log

---

pkg/cloudevents/generic/options/kafka/options.go

ref to https://github.com/confluentinc/confluent-kafka-dotnet/issues/957 https://github.com/confluentinc/librdkafka/issues/1072
> Also, ALL_BROKERS_DOWN doesn't really mean anything to librdkafka, it is just a friendly indication to the application that currently there are no brokers to communicate with. But librdkafka will continue to try to reconnect indefinately, and it will attempt to re-send messages until message.timeout.ms or message.max.retries are exceeded.
It throws error in our case so that the sourceclient or agentclient will be restarted. that is not our desired behaviour.
Fixes #
```
E0515 11:14:48.057462    6304 baseclient.go:92] the cloudevents client is disconnected, client error 2/2 brokers are down
I0515 11:14:48.058680    6304 baseclient.go:199] stop the cloudevents …
```

:bug: ALL_BROKERS_DOWN doesn't really mean anything to librdkafka

---

pkg/cloudevents/generic/optionsbuilder_kafka_test.go
pkg/cloudevents/generic/optionsbuilder_test.go
test/integration/cloudevents/cloudevents_kafka_test.go
test/integration/cloudevents/suite_test.go

:bug: eliminate the IDE errors when editing the code

---

pkg/cloudevents/generic/options/mqtt/options.go
pkg/cloudevents/generic/options/mqtt/options_test.go
pkg/cloudevents/generic/optionsbuilder_kafka_test.go
pkg/cloudevents/generic/optionsbuilder_test.go
test/integration/cloudevents/cloudevents_kafka_test.go
test/integration/cloudevents/suite_test.go

:sparkles: make mqtt ca config optional

---

pkg/cloudevents/generic/sourceclient.go
pkg/cloudevents/work/agent/codec/manifest.go
pkg/cloudevents/work/agent/codec/manifestbundle.go
test/integration/cloudevents/cloudevents_test.go

https://github.com/open-cluster-management-io/ocm/issues/492

🐛 fix agent resyncs the deleted spec from source

---

pkg/cloudevents/work/payload/manifestbundle.go
pkg/cloudevents/work/source/codec/manifestbundle.go
pkg/cloudevents/work/source/codec/manifestbundle_test.go

:seedling: add ManifestBundle to ManifestBundleStatus as an optional field

---

pkg/cloudevents/README.md

This PR tries to add document for garbage collector for cloudevents work client, as a follow up PR for https://github.com/open-cluster-management-io/sdk-go/pull/36
Fixes #

📖 add doc for garbage collector.

---

pkg/cloudevents/work/source/codec/manifestbundle.go
pkg/cloudevents/work/source/codec/manifestbundle_test.go

:seedling: set work meta data to ManifestBundle event on source

---

pkg/cloudevents/work/store/informer.go

:bug: should use the updated work when update the cache for cloudevents client

---

pkg/cloudevents/work/clientbuilder.go

:bug: always receive the reconnected signal to avoid client blocking

---

pkg/cloudevents/generic/options/grpc/options.go

If the grpc client is connected, when the grpc connections is down, the grpc connection state will change from Ready to Idle, the `TRANSIENT_FAILURE` seems only happened when establishing the connection

:bug: handle grpc idle status

---

pkg/cloudevents/work/source/client/manifestwork.go

:seedling: try to get the work resource version from itself

---

pkg/cloudevents/work/source/client/manifestwork.go
pkg/cloudevents/work/utils/utils.go
pkg/cloudevents/work/utils/utils_test.go
test/integration/cloudevents/manifestworkclients_watch_test.go
test/integration/cloudevents/util/work.go

:seedling: ensure the work's manifest is decoded

---

pkg/apis/cluster/v1alpha1/score.go
pkg/apis/cluster/v1alpha1/score_test.go

Ref: https://github.com/open-cluster-management-io/ocm/issues/68
Fixes #

:seedling: provide a normalize library to generate scores for AddOnPlacementScore

---

pkg/cloudevents/README.md
pkg/cloudevents/doc/design.md

:seedling: add docs for cloudevents

---

pkg/cloudevents/work/agent/client/manifestwork.go
pkg/cloudevents/work/errors/errors.go
pkg/cloudevents/work/source/client/manifestwork.go
pkg/cloudevents/work/store/base.go
pkg/cloudevents/work/store/informer.go
pkg/cloudevents/work/store/interface.go
pkg/cloudevents/work/store/local.go
pkg/cloudevents/work/utils/utils.go

:seedling: using kube api errors for work clients

---

pkg/cloudevents/work/agent/client/manifestwork.go
pkg/cloudevents/work/agent/lister/lister.go
pkg/cloudevents/work/source/client/manifestwork.go
pkg/cloudevents/work/source/lister/lister.go
pkg/cloudevents/work/store/base.go
pkg/cloudevents/work/store/interface.go

:seedling: change watchstore list return value type to supporting list continue

---

pkg/cloudevents/generic/agentclient.go
pkg/cloudevents/generic/sourceclient.go
pkg/cloudevents/generic/types/types.go
pkg/cloudevents/work/agent/lister/lister.go
pkg/cloudevents/work/source/lister/lister.go
test/integration/cloudevents/manifestworkclients_reync_test.go

:bug: support filter the resource with its related event data type

---

pkg/cloudevents/work/agent/client/manifestwork.go

:bug: avoid race conditions among the agent's go routines

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/api/addon/v1alpha1/types_managedclusteraddon.go

🌱 Update api to v0.15.0

---

pkg/cloudevents/generic/agentclient.go
pkg/cloudevents/generic/agentclient_test.go
pkg/cloudevents/generic/baseclient.go
pkg/cloudevents/generic/metrics_collector.go
pkg/cloudevents/generic/metrics_collector_test.go
pkg/cloudevents/generic/options/fake/fakeoptions.go
pkg/cloudevents/generic/sourceclient.go
pkg/cloudevents/work/agent/client/manifestwork.go
pkg/cloudevents/work/source/client/manifestwork.go

This pull request adds metrics for CloudEvents to the SDK. The aim is to provide better observability for events processed by the SDK.
Fixes #

🌱 add cloudevents metrics.

---

pkg/cloudevents/generic/baseclient.go

log the whole event with trace level to avoid large output in debug level

:seedling: log the whole event with trace level

---

pkg/cloudevents/generic/sourceclient_test.go
pkg/cloudevents/server/grpc/server.go
pkg/cloudevents/server/grpc/server_test.go
pkg/cloudevents/server/interface.go
pkg/cloudevents/server/store.go
test/integration/cloudevents/cloudevents_kafka_test.go

✨ Define grpc server interface

---

pkg/cloudevents/clients/cluster/client.go
pkg/cloudevents/clients/cluster/client_test.go
pkg/cloudevents/clients/cluster/clientholder.go
pkg/cloudevents/clients/cluster/codec.go
pkg/cloudevents/clients/cluster/wrapper.go
pkg/cloudevents/clients/csr/client.go
pkg/cloudevents/clients/csr/client_test.go
pkg/cloudevents/clients/csr/clientholder.go
pkg/cloudevents/clients/csr/codec.go
pkg/cloudevents/generic/agentclient.go

:seedling: cluster and csr clients

---

pkg/cloudevents/clients/cluster/codec.go
pkg/cloudevents/clients/csr/client.go
pkg/cloudevents/clients/csr/client_test.go
pkg/cloudevents/clients/csr/codec.go
pkg/cloudevents/clients/store/lister.go
pkg/cloudevents/clients/store/lister_test.go
pkg/cloudevents/generic/options/grpc/options.go
pkg/cloudevents/generic/options/grpc/options_test.go
pkg/cloudevents/server/grpc/server.go
test/integration/cloudevents/util/grpc.go

1. set resource version in codec with string type
2. Do not check source in lister
3. allow setting token for grpc connection
Fixes #

🐛  Fix several bugs in cloudevent library

---

pkg/cloudevents/clients/utils/utils.go
pkg/cloudevents/clients/utils/utils_test.go

:seedling: support StrategicMergePatchType

---

pkg/cloudevents/server/grpc/options/server.go
pkg/cloudevents/server/grpc/server.go
pkg/cloudevents/server/grpc/server_test.go
pkg/cloudevents/server/interface.go

:seedling: decouple the grpc service registration and starting a grpc server

---

pkg/cloudevents/generic/options/grpc/options.go

:bug: do not reconnect the grpc server when connection is idle

---

pkg/cloudevents/server/grpc/server.go
pkg/cloudevents/server/interface.go

:seedling: get the grpc server subscribers

---

pkg/cloudevents/generic/options/grpc/options.go
pkg/cloudevents/generic/options/grpc/protocol/protocol.go

1. rollback the grpc idle status handling for server restart
2. make sure the client connection can be closed when cancel the context
Fixes #

:bug:  handle the grpc idle conn
